export const VERIFIED_DOCTOR_QUERY = `
query FindDoctorsByVerificationStatus($is_verified: Boolean!) {
  findDoctorsByVerificationStatus(is_verified: $is_verified) {
      id
    online
    first_name
    last_name
    email
    phone_number
    gender
    is_verified
    verification_code
    verification_code_expiry
    image
    city
    country
    department
    experience
    registration_no
    qualification
    consultation_mode
    consultation_fee_regular
    consultation_fee_discounted
    booking_lead_time
    payout_method
    payout_method_id
    address
    postal_code
    services
    specialization
    bibliography
    work
    degree
    designation
    enterSymptom
    institute
    ac_no
    upi_id
  }
}
`;